name: Build and Package Next.js Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' 
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci 

      - name: Run tests
        run: npm run test || echo "Tests step skipped if not configured"
      
      - name: Build Next.js application
        run: npm run build
      
      - name: Create production bundle
        run: |
          mkdir -p build-output
          cp -r .next build-output/
          cp -r public build-output/
          cp package.json build-output/
          cp package-lock.json build-output/
          cp next.config.js build-output/ || echo "No next.config.js file found"
          
          # Crear un archivo simple de instrucciones
          echo "# Challenge Puntospoint" > build-output/README.md
          echo "Para ejecutar la app:" >> build-output/README.md
          echo "1. Extraer el archivo ZIP" >> build-output/README.md
          echo "2. Ejecutar 'npm install --production'" >> build-output/README.md
          echo "3. Ejecutar 'npm start'" >> build-output/README.md
      
      - name: Create ZIP archive
        run: |
          cd build-output
          zip -r ../nextjs-build.zip .
          cd ..
      
      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: nextjs-build.zip
          retention-days: 7 